name: Deploy Testing Branch to Testing Environment

on:
  push:
    branches:
      - testing

jobs:
  deploy-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: testing

      - name: Setup SSH Key
        run: |
          echo "${{ secrets.DEPLOY_KEY }}" > deploy_key
          chmod 600 deploy_key
          mkdir -p ~/.ssh

      - name: Create Ansible Inventory File
        run: |
          echo "${{ secrets.deploy_server_inventory }}" > inventory.ini

      - name: Extract Host IP and Add to known_hosts
        run: |
          host_ip=$(awk '{print $1}' inventory.ini)
          echo "Connecting to IP: $host_ip"
          ssh-keyscan -H "$host_ip" >> ~/.ssh/known_hosts

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Setup Node.js for Frontend Build
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install and Build Frontend
        run: |
          cd apps/frontend
          npm install
          npx vite build
          cd ../..

      - name: Rsync Code to Server
        run: |
          host_ip=$(awk '{print $1}' inventory.ini)
          ansible "$host_ip" -i inventory.ini -m synchronize -a "src=./ dest=/home/deploy-folder/ delete=yes recursive=yes" \
            --private-key=deploy_key

      - name: Rsync dist to temp folder
        run: |
          host_ip=$(awk '{print $1}' inventory.ini)
          ansible "$host_ip" -i inventory.ini -m synchronize -a "src=./apps/frontend/dist/ dest=/home/lakshmikanth/tmp-dist/ delete=yes recursive=yes" \
            --private-key=deploy_key

      - name: Move dist to /var/www/html/testing with sudo
        run: |
          host_ip=$(awk '{print $1}' inventory.ini)
          ansible "$host_ip" -i inventory.ini -m shell -a "\
            sudo rm -rf /var/www/html/testing* && \
            sudo cp -r /home/lakshmikanth/tmp-dist/* /var/www/html/testing" \
            --private-key=deploy_key 