name: Dump EC2 Secrets to Files

on:
  push:
    branches:
      - ssh-test
  workflow_dispatch:

jobs:
  ssh-test:
    runs-on: ubuntu-latest

    steps:
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_PEM_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

        echo "HOST=${{ secrets.EC2_HOST }}"
        echo "USER=${{ secrets.EC2_USER }}"

        HOST="${{ secrets.EC2_HOST }}"
        USER="${{ secrets.EC2_USER }}"

        ssh-keyscan -H "$HOST" >> ~/.ssh/known_hosts
        ssh -o StrictHostKeyChecking=no "$USER@$HOST" "echo 'Connected to EC2 via inline test'"

